#  NumPy және Машиналық Оқыту үшін Python Негіздері

**Тапсырма саны:** 10  

##  Нұсқаулық

Төмендегі 10 тапсырманың әрқайсысында `# КОДТЫ ОСЫНДА ЖАЗ` деген белгі бар. Сол жерге өз шешімінді жаз.


In [ ]:
# Қажетті кітапханаларды импорттау
import numpy as np
import math

: 

# I Бөлім: NumPy Кітапханасымен Жұмыс

**NumPy** (Numerical Python) сандық есептеулерге арналған Python кітапханасы. Ол көп өлшемді массивтермен (ndarray) жұмыс істеуге, математикалық операциялар жүргізуге және деректерді өңдеуге мүмкіндік береді. Машиналық оқытуда NumPy матрицалық есептеулер мен деректер алдын ала өңдеуінің негізі болып табылады.

> **Тапсырмалар 1–5:** NumPy массивтерін құру, индекстеу, операциялар және статистика.

## Тапсырма 1: NumPy Массивін Құру және Негізгі Сипаттамалар

**Мақсат:** NumPy массивін қолмен жасау және оның қасиеттерін зерттеу.

**Шарт:**

1. `[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]` мәндерінен тұратын NumPy массивін жаса.
2. Массивтің мынадай сипаттамаларын экранға шығар:
   - Өлшемі (`shape`)
   - Деректер типі (`dtype`)
   - Элементтер саны (`size`)
   - Өлшемдер саны (`ndim`)

**Күтілетін нәтиже үлгісі:**
```
Массив: [ 10  20  30  40  50  60  70  80  90 100]
Өлшемі: (10,)
Деректер типі: int64
Элементтер саны: 10
Өлшемдер саны: 1
```

In [7]:
# Тапсырма 1: NumPy массивін құру

# КОДТЫ ОСЫНДА ЖАЗ
import numpy as np

arr = np.array([10, 30, 40, 50, 60, 70, 80, 90, 100])
print(f"olshemi: {arr.shape}")
print(f"derekter tipi: {arr.dtype}")
print(f"elementter sany: {arr.size}")
print(f"olshemder sany: {arr.ndim}")

olshemi: (9,)
derekter tipi: int64
elementter sany: 9
olshemder sany: 1


## Тапсырма 2: Матрица Құру және Матрицалық Операциялар

**Мақсат:** 2D массив (матрица) жасау және негізгі матрицалық операцияларды орындау.

NumPy-да матрицалар 2 өлшемді ndarray ретінде сақталады. Машиналық оқытуда деректер жиыны көбінесе (n_samples × n_features) пішіндегі матрица түрінде ұсынылады. Матрицалық операциялар линейлі регрессия, нейрондық желілер және басқа алгоритмдердің негізін қалайды.

**Шарт:**

1. Мынадай 3×3 матрицаны жаса:
```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```
2. Осы матрицаны **транспонирлей** (`.T`).
3. Матрицаны өзіне **матрицалық көбейт** (`np.dot` немесе `@`).
4. Нәтижелерді экранға шығар.

In [14]:
# Тапсырма 2: Матрица және матрицалық операциялар
import numpy as np
# КОДТЫ ОСЫНДА ЖАЗ
x = np.array([[1,2,3], 
              [4,5,6],
              [7,8,9]])
print(x.dot(x))
print("================================")
print(x.transpose().dot(x))





[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]


## Тапсырма 3: Индекстеу, Тілімдеу (Slicing) және Сүзгілеу

**Мақсат:** NumPy массивіндегі элементтерге индекс арқылы қол жеткізу және шарт бойынша сүзу.

NumPy-да Boolean маска — шартқа сай элементтерді таңдаудың тиімді тәсілі. Мысалы, деректерден аномалиялар немесе белгілі бір диапазондағы мәндерді жылдам алып тастауға болады. Бұл алдын ала өңдеу (preprocessing) кезеңінде жиі қолданылады.

**Шарт:**

1. 1-ден 20-ға дейінгі сандардан тұратын массив жаса (`np.arange`).
2. Массивтің **алғашқы 5** элементін шығар.
3. Массивтің **соңғы 5** элементін шығар.
4. Массивтің **жұп индекстегі** элементтерін шығар (0, 2, 4, ...).
5. Мәні **10-нан үлкен** элементтерді ғана шығар (Boolean индекстеу).

In [19]:
# Тапсырма 3: Индекстеу, тілімдеу және сүзгілеу
import numpy as np
import math
# КОДТЫ ОСЫНДА ЖАЗ
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(arr[0:5])
print(arr[-1:-6:-1])

temp =np.array([])
for num in arr:
    if num%2 == 0:
        temp =np.append(temp, num)
print(temp)



[1 2 3 4 5]
[20 19 18 17 16]
[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


## Тапсырма 4: Статистикалық Функциялар

**Мақсат:** NumPy-дың кірістірілген статистикалық функцияларын пайдалану.

Деректерді зерттеудің (EDA) бірінші қадамы — негізгі статистикалық көрсеткіштерді есептеу. Орташа мән, медиана, стандартты ауытқу және персентильдер деректер таралуын түсінуге көмектеседі. NumPy бұл есептеулерді векторланған түрде өте жылдам орындайды.

**Шарт:**

`np.random.seed(42)` арқылы кездейсоқтықты бекіт, содан кейін 0-ден 100-ге дейінгі **50 кездейсоқ бүтін сан** жаса.

Келесі статистикалық көрсеткіштерді есепте және шығар:
- Минимум және максимум
- Орташа мән (mean)
- Медиана
- Стандартты ауытқу
- Дисперсия
- 25-ші және 75-ші персентильдер

In [20]:
# Тапсырма 4: Статистикалық функциялар
np.random.seed(42)  # Қайталануы үшін кездейсоқтықты бекіту

import numpy as np 
import math as m 
import random as random


arr = np.random.randint(0,100,size = 50)
print(arr)
print(f"maximum: {arr.max()}")
print(f"minimum: {arr.min()}")
print(f"mean: {arr.mean()}")
print(f"median: {np.median(arr)}")
print(f"std {np.std(arr)}")
print(f"dispersion {np.var(arr)}")
print(f"25 Percentile: {np.percentile(arr,25)}")
print(f"75  Percentile: {np.percentile(arr,75)}")


# КОДТЫ ОСЫНДА ЖАЗ


[51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37  1 63 59 20
 32 75 57 21 88 48 90 58 41 91 59 79 14 61 61 46 61 50 54 63  2 50  6 20
 72 38]
maximum: 99
minimum: 1
mean: 50.84
median: 55.5
std 27.849854577717277
dispersion 775.6144
25 Percentile: 24.5
75  Percentile: 73.5


## Тапсырма 5: Пішінді Өзгерту (Reshape) және Хабарлау (Broadcasting)

**Мақсат:** Массив пішінін өзгерту және NumPy broadcasting механизмін түсіну.

Broadcasting  NumPy-дың әртүрлі пішіндегі массивтерге автоматты түрде арифметикалық операция қолдану мүмкіндігі. Reshape функциясы деректерді нейрондық желілерге немесе sklearn модельдеріне беру алдында жиі қолданылады.

**Шарт:**

1. 1-ден 12-ге дейінгі сандардан тұратын массив жаса (`np.arange`).
2. Оны **3×4 матрицаға** түрлендір (`reshape`).
3. Матрицаның **әр жолына** `[10, 20, 30, 40]` векторын қос (broadcasting).
4. Матрицаның **әр бағанын** `[[1], [2], [3]]` бағандық векторына көбейт (broadcasting).
5. Нәтижелерді шығар.

In [25]:
# Тапсырма 5: Reshape және Broadcasting

# КОДТЫ ОСЫНДА ЖАЗ
import numpy as np
import math

arr = np.arange(1,13)
print(arr)
print("\n")
arr = arr.reshape(3,4)
print(arr)
print("\n")
v_row = np.array([10,20,30,40])
arr_result = arr + v_row
print(arr_result)
print("\n")

v_col = np.array([[1],[2],[3]])
arr_result_col = arr * v_col
print(arr_result_col)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]


[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


# II Бөлім: Машиналық Оқыту үшін Python Негіздері

Python-ның функциялары мен кластары машиналық оқыту жүйелерін модульдік және қайта пайдалануға болатын түрде құруға мүмкіндік береді. ML pipeline-дарын, деректерді өңдеу логикасын және модель архитектурасын таза кодпен ұйымдастыру үшін OOP принциптері өте маңызды. scikit-learn кітапханасының өзі де осындай кластық құрылымға негізделген.

> **Тапсырмалар 6–10:** Функциялар, декораторлар, кластар және ML компоненттерін модельдеу.

## Тапсырма 6: ML Алдын Ала Өңдеу Функциялары

**Мақсат:** Деректерді нормализациялайтын және стандарттайтын функциялар жазу.

Нормализация мен стандарттау — ML алгоритмдерінің дұрыс жұмыс істеуі үшін маңызды алдын ала өңдеу қадамдары. Min-Max нормализациясы мәндерді [0, 1] диапазонына, Z-score стандарттауы орташа мәнді 0, стандартты ауытқуды 1 етіп түрлендіреді. Бұл SVM, KNN, нейрондық желі сияқты алгоритмдер үшін өте маңызды.

**Шарт:**

Екі функция жаз:

**`min_max_normalize(arr)`** — Min-Max нормализациясы:
$$x_{norm} = \frac{x - x_{min}}{x_{max} - x_{min}}$$

**`z_score_standardize(arr)`** — Z-score стандарттауы:
$$x_{std} = \frac{x - \mu}{\sigma}$$

Екі функцияны да `[2, 4, 4, 4, 5, 5, 7, 9]` массивіне қолдан және нәтижені шығар.

In [27]:
# Тапсырма 6: Нормализация және стандарттау функциялары
import numpy as np
# КОДТЫ ОСЫНДА ЖАЗ
arr = np.array([2,4,4,4,5,5,7,9])

def min_max_normalize(arr):
    return (arr - arr.min()) / (arr.max() - arr.min())

def z_score_standardize(arr):
    return (arr - arr.mean()) / arr.std()

normalized_arr = min_max_normalize(arr)
standardized_arr = z_score_standardize(arr)
print(f"normalized array: {normalized_arr}")
print(f"standardized array: {standardized_arr}")


normalized array: [0.         0.28571429 0.28571429 0.28571429 0.42857143 0.42857143
 0.71428571 1.        ]
standardized array: [-1.5 -0.5 -0.5 -0.5  0.   0.   1.   2. ]


## Тапсырма 7: Рекурсия және Lambda Функциялар

**Мақсат:** Рекурсивті функция және lambda өрнектерін ML контекстінде қолдану.

Lambda функциялар — атаусыз шағын функциялар, ML-де деректерді трансформациялау үшін `map()`, `filter()`, `sorted()` функцияларымен жиі қолданылады. Рекурсия болса күрделі алгоритмдерді (мысалы, шешім ағашының тереңдігін есептеу) элегантты жазуға мүмкіндік береді.

**Шарт:**

1. **Рекурсивті функция:** `factorial(n)` — n! санын рекурсия арқылы есепте.
2. **Lambda:** `[0.1, 0.5, 0.9, 1.5, -0.3, 2.0]` тізімінен тек `[0, 1]` диапазонындағы мәндерді `filter` + `lambda` арқылы алып шығар.
3. **Lambda + map:** `[-2, -1, 0, 1, 2]` тізіміндегі әр элементке ReLU активация функциясын `map` + `lambda` арқылы қолдан.

> ReLU(x) = max(0, x)

In [4]:
# Тапсырма 7: Рекурсия және Lambda функциялар
import numpy as np 
# КОДТЫ ОСЫНДА ЖАЗ

def factorial(n):
    if (n==0):
        return 1
    elif (n==1):
        return 1
    else:
        return n* factorial(n-1)
        
print(factorial(5))


arr =np.array([0.1 , 0.5, 0.9, 1.5, -0.3, 2.0 ])
x = filter(lambda z: 0 < z < 1, arr)
print(np.array(list(x)))



arr_2 = np.array([-2 ,-1 ,0, 1, 2])
def relu(x):
    z = lambda x: x if x > 0 else 0
    mapped = map(z,x)
    return np.array(list(mapped))

print(relu(arr_2))


120
[0.1 0.5 0.9]
[0 0 0 1 2]


## Тапсырма 8: Кластар — ML Метрикаларын Есептеуші

**Мақсат:** OOP принциптерін пайдаланып, классификация метрикаларын есептейтін класс жазу.

Машиналық оқытуда модель сапасын бағалау үшін Accuracy, Precision, Recall, F1-score метрикалары қолданылады. Оларды бір класс ішінде топтастыру кодтың модульдігін арттырады және sklearn-дің `classification_report` функциясына ұқсас нәтиже береді.

**Шарт:**

`ClassificationMetrics` атты класс жаз. Конструктор `y_true` (нақты мәндер) және `y_pred` (болжамдар) параметрлерін қабылдасын.

Класта мынадай әдістер болуы керек:
- `accuracy()` — дұрыс болжамдар үлесі
- `precision()` — дәлдік: TP / (TP + FP)
- `recall()` — толықтық: TP / (TP + FN)
- `f1_score()` — F1: 2 × (precision × recall) / (precision + recall)
- `report()` — барлық метрикаларды форматталған түрде шығарады

Тест деректері:
```python
y_true = [1, 0, 1, 1, 0, 1, 0, 0, 1, 0]
y_pred = [1, 0, 1, 0, 0, 1, 1, 0, 1, 0]
```

In [26]:
# Тапсырма 8: ClassificationMetrics класы

# Тест деректері
y_true = [1, 0, 1, 1, 0, 1, 0, 0, 1, 0]  # Нақты белгілер
y_pred = [1, 0, 1, 0, 0, 1, 1, 0, 1, 0]  # Болжамдар

# КОДТЫ ОСЫНДА ЖАЗ

class ClassificatonMetrics:
    def __init__(self, y_true , y_pred):
        self.y_true = y_true
        self.y_pred = y_pred
        
    def accuracy(self):
        correct = 0
        for t,p in zip(self.y_true, self.y_pred):
            if t == p:
                correct +=1
        return (correct/(len(self.y_true))) 
    
    def percision(self):
        tp = 0
        fp = 0
        
        for t,p in zip(self.y_true, self.y_pred):
            if p==1 and t ==1:
                tp +=1
            elif p==0 and t ==1:
                fp+=1
        return (tp/(fp+tp))
    
    def recall(self):
        tp = 0
        fn = 0
        
        for t,p in zip(self.y_true, self.y_pred):
            if p==1 and t ==1:
                tp +=1
            elif p==0 and t ==1:
                fn+=1
        return (tp/(fn+tp))
    
    def f1_score(self):
        p = self.percision()
        r = self.recall()
        return 2*((p*r)/(p+r))
    
    def report(self):
        
        print(f"accuracy{self.accuracy()}")
        print(f"percision{self.percision()}")
        print(f"recall {self.recall()}")
        print(f"score {self.f1_score()}")
        

x = ClassificatonMetrics(y_true, y_pred)
x.report()


accuracy0.8
percision0.8
recall 0.8
score 0.8000000000000002


## Тапсырма 9: Мұрагерлік (Inheritance) — ML Модель Иерархиясы

**Мақсат:** Python-да кластар иерархиясын (мұрагерлік) пайдаланып ML модельдерін модельдеу.

Мұрагерлік (inheritance) — OOP-тың негізгі принципі. scikit-learn барлық модельдерін `BaseEstimator` базалық класынан туындатады, бұл `fit()`, `predict()`, `score()` сияқты ортақ интерфейсті қамтамасыз етеді. Осы паттернді түсіну ML кітапханаларының архитектурасын жобалауға негіз береді.

**Шарт:**

1. **`BaseModel`** — базалық класс:
   - `__init__(self, model_name)` — модель атын сақтайды
   - `fit(X, y)` — `NotImplementedError` шығарады (абстрактілі)
   - `predict(X)` — `NotImplementedError` шығарады (абстрактілі)
   - `describe()` — модель туралы ақпаратты шығарады

2. **`LinearRegressionModel(BaseModel)`** — туынды класс:
   - `fit(X, y)` — `np.linalg.lstsq` арқылы коэффициенттерді табады
   - `predict(X)` — `X @ weights` арқылы болжайды
   - `describe()` — базалық сипаттаманы + коэффициенттерді шығарады

3. Тест деректерінде `fit` → `predict` → `describe` тізбегін шақыр.

In [10]:
# Тапсырма 9: Мұрагерлік — ML Модель Иерархиясы
import numpy as np
import random as random
# Тест деректері
np.random.seed(0)
X_train = np.column_stack([np.ones(20), np.random.randn(20)])  # Бір фичалы деректер
y_train = 3 * X_train[:, 1] + 5 + np.random.randn(20) * 0.5  # y = 3x + 5 + шу

# КОДТЫ ОСЫНДА ЖАЗ

class BaseModel:
    def __init__(self, model_name):
        self.model_name = model_name
        
    def fit(self, x, y):
        pass
    
    def predict(self, x ):
        pass
    
    def describe(self):
        print(f"fit {self.fit}")
        print(f"predict {self.predict}")
        
class LinearRegressionModel(BaseModel):
    def __init__(self, model_name):
        super().__init__(model_name)
        self.weights = None
        
    def fit(self, x ,y):
        x = np.array(x)
        y = np.array(y)
        self.weights = np.linalg.lstsq(x, y, rcond=None)[0]
        
    def predict(self, x):
        x = np.array(x)
        return x.dot(self.weights)
    
    def describe(self):
        return super().describe()
        print(f"weights {self.weights}")
        
model = LinearRegressionModel("Linear Regression")
model.fit(X_train, y_train)

predictions = model.predict(X_train)
print(f"Predictions: {predictions}\n")
print(predictions)

model.describe()



Predictions: [10.39296444  6.21801927  7.98908139 11.85259602 10.70979994  2.0016277
  7.90138376  4.52980851  4.67716221  6.24998055  5.43404376  9.4447173
  7.32269098  5.36557259  6.3518054   6.01451214  9.56656395  4.36512103
  5.95143432  2.37869384]

[10.39296444  6.21801927  7.98908139 11.85259602 10.70979994  2.0016277
  7.90138376  4.52980851  4.67716221  6.24998055  5.43404376  9.4447173
  7.32269098  5.36557259  6.3518054   6.01451214  9.56656395  4.36512103
  5.95143432  2.37869384]
fit <bound method LinearRegressionModel.fit of <__main__.LinearRegressionModel object at 0x7cbcfbfef380>>
predict <bound method LinearRegressionModel.predict of <__main__.LinearRegressionModel object at 0x7cbcfbfef380>>


## !КҮРДЕЛІ
##Тапсырма 10: Толыққанды ML Pipeline Класы

**Мақсат:** Нақты ML жүйесін модельдейтін толыққанды Pipeline класын жазу.

ML Pipeline  деректерді алдын ала өңдеу, модельді оқыту және бағалау қадамдарын автоматты реттілікпен орындайтын құрылым. sklearn-дің `Pipeline` класы осындай принципте жұмыс істейді. Мұны өз бетімен жүзеге асыру бүкіл ML жұмыс ағынын терең түсінуге мүмкіндік береді.

**Шарт:**

`MLPipeline` класы жаз, ол мынадай кезең-кезеңді іске асырсын:

1. **`load_data(X, y)`** — деректерді сақтайды
2. **`train_test_split(test_ratio=0.2)`** — деректерді оқыту/тест жиынтықтарына бөледі
3. **`normalize()`** — оқыту жиынтығы бойынша Min-Max нормализациясын жасайды (тест жиынына да қолданады)
4. **`train()`** — `np.linalg.lstsq` арқылы линейлі регрессия оқытады
5. **`evaluate()`** — MSE және R² метрикаларын есептейді
6. **`run()`** — барлық қадамдарды дұрыс ретпен шақырады

Тест деректерінде толық `run()` жүргіз және нәтижені шығар.

> **Кеңес:** R² = 1 - SS_res / SS_tot, мұндағы SS_res = Σ(y - ŷ)², SS_tot = Σ(y - ȳ)²

In [16]:
# Тапсырма 10: Толыққанды ML Pipeline класы

# Тест деректері
import numpy as np

# test data
np.random.seed(42)
n_samples = 100
X_data = np.random.randn(n_samples, 3)
y_data = 2 * X_data[:,0] - 1.5 * X_data[:,1] + 0.5 * X_data[:,2] + np.random.randn(n_samples) * 0.3


class MLPipeline:

    def __init__(self):
        self.X = None
        self.y = None

    def load_data(self, X, y):
        self.X = X
        self.y = y

    def train_test_split(self, test_ratio=0.2):

        n = len(self.X)
        test_size = int(n * test_ratio)

        self.X_train = self.X[:-test_size]
        self.X_test = self.X[-test_size:]

        self.y_train = self.y[:-test_size]
        self.y_test = self.y[-test_size:]



    def normalize(self):

        self.min = np.min(self.X_train, axis=0)
        self.max = np.max(self.X_train, axis=0)

        self.X_train = (self.X_train - self.min) / (self.max - self.min)
        self.X_test = (self.X_test - self.min) / (self.max - self.min)



    def train(self):

        X_bias = np.column_stack((np.ones(len(self.X_train)), self.X_train))

        self.weights = np.linalg.lstsq(X_bias, self.y_train, rcond=None)[0]



    def predict(self, X):

        X_bias = np.column_stack((np.ones(len(X)), X))

        predictions = X_bias @ self.weights

        return predictions

    def evaluate(self):

        y_pred = self.predict(self.X_test)

        mse = np.mean((self.y_test - y_pred) ** 2)

        ss_res = np.sum((self.y_test - y_pred) ** 2)
        ss_tot = np.sum((self.y_test - np.mean(self.y_test)) ** 2)

        r2 = 1 - ss_res / ss_tot

        print("MSE:", mse)
        print("R2:", r2)

    def run(self):

        self.train_test_split()
        self.normalize()
        self.train()
        self.evaluate()


pipeline = MLPipeline()

pipeline.load_data(X_data, y_data)

pipeline.run()


MSE: 0.11711216530265836
R2: 0.9827905620387998


# Қорытынды және Өзін-өзі Бағалау

(міндетті емес) Барлық тапсырмаларды орындап болған соң, төмендегі кестені толтыр:

| Тапсырма | Тақырып | Орындалды? | Қиындықтар |
|:--------:|---------|:----------:|------------|
| 1 | NumPy массиві және сипаттамалар | ☐ | |
| 2 | Матрица және матрицалық операциялар | ☐ | |
| 3 | Индекстеу және сүзгілеу | ☐ | |
| 4 | Статистикалық функциялар | ☐ | |
| 5 | Reshape және Broadcasting | ☐ | |
| 6 | Нормализация функциялары | ☐ | |
| 7 | Рекурсия және Lambda | ☐ | |
| 8 | ClassificationMetrics класы | ☐ | |
| 9 | Мұрагерлік — ML иерархиясы | ☐ | |
| 10 | ML Pipeline класы | ☐ | |

---

**Пікір (міндетті емес):**

_Осы үй жұмысын орындау барысында не үйрендің? Қандай тапсырма ең қызықты болды?_


---